version: '3'
services:
  nodejs:
      build:
         context: .
        # dockerfile: Dockerfile
      # image: nodejs
      # container_name: nodejs
      #restart: unless-stopped
      # env_file: ./config/config.env
      # environment:
      #   - NODE_ENV=production
      ports:
        - "3000:3000"
      links:
        - mongodb
      depends_on:
        - mongodb


  mongodb:
      image: mongo:latest
      container_name: "mongo"
      env_file: ./config/config.env
      volumes:
          - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --logpath=/dev/null # --quiet


  mongo_seed:
    image: mongo:latest
    # links:
    #   - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh