version: "3"
services:
    app:
      container_name: "audienceKit"
      restart: always
      build: .
      ports:
        - '3800:3800'
      links:
        - mongo
    mongo:
      container_name: localhost
      image: mongo
      ports:
      - '27017:27017'