version: '3'
services:
  nodejs:
      build:
         context: .
        #  dockerfile: Dockerfile
      # image: nodejs
      container_name: "audienceApi" 
      #restart: unless-stopped
      # env_file: ./config/config.env
      # environment:
      #    - NODE_ENV=production
      env_file: ./config/config.env
      ports:
        - "3000:3000"
      links:
        - mongodb
      # environment:
      # - SECRET_KEY_BASE=secret
      # - MONGO_URL=mongodb://mongodb:27017/audienceKit
      # depends_on:
      #   - mongodb


  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      env_file: ./config/config.env
      volumes:
          - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --logpath=/dev/null # --quiet


  mongo_seed:
    image: mongo:latest
    # links:
    #   - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh