version: '3'
services:
  nodejs:
      build:
        context: .
        dockerfile: Dockerfile
      image: nodejs
      container_name: audience_api
      restart: unless-stopped
      env_file: ./config/config.env
      # environment:
      #   - MONGO_USERNAME=$MONGO_USERNAME
      #   - MONGO_PASSWORD=$MONGO_PASSWORD
      #   - MONGO_HOSTNAME=db
      #   - MONGO_PORT=$MONGO_PORT
      #   - MONGO_DB=$MONGO_DB
      ports:
        - "3000:3000"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh